# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Commented out IPython magic to ensure Python compatibility.
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

import statistics

#Mean,Median,Mode
df=sns.load_dataset('tips')
df.head()

np.mean(df['total_bill'])

np.median(df['total_bill'])

statistics.mode(df['total_bill'])

sns.boxplot(x=df['total_bill'])

sns.histplot(x=df['total_bill'],kde=True)

df1=sns.load_dataset('iris')

df1.head()

sns.histplot(x=df1['sepal_width'],kde=True)

sns.countplot(df1['species'])

np.percentile(df1['sepal_length'],[25,75])

